### ISSUE TITLE
Could you provide all within tissue significant result?

### ISSUE THREAD

**Issue by tianwen0003** [LappalainenLab/TF-eQTL#1]
Hi
I noticed your plos genetic paper only published the TF-eQTL with at least two evidence in supplementary table and the wihin tissue result file in github only contains a server path. I am wondering if you could provide all within tissue significant results. I want to check the its overlap with my TF-eQTL results to get more confident result.

**Comment by eflynn90** [comment]
Hello, the files are now added in `data_tables/tf_eqtls/` (https://github.com/LappalainenLab/TF-eQTL/tree/main/data_tables/tf_eqtls)
