### ISSUE TITLE
gene expression value used for interaction term

### ISSUE THREAD

**Issue by tianwen0003** [LappalainenLab/TF-eQTL#2]
Hi
I think I know the expression phenotype you used for tensorqtl analysis is inverse normal tranformed gene expression value, But I don't known the expression value used for genotype interaction term is TPM, log transformed TPM or inverse normal tranformed gene expression

**Comment by eflynn90** [comment]
Hello, I believe the gene expression values and the TF expression values for the tensorqtl analysis were the same data type, both inverse normal transformed gene expression.
